site_name: Xamarin Forms Guide - Peruzal
site_description: An introductory guide to developing cross platform mobile apps for Android and iOS with Xamarin Forms
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'amber'
    accent: 'deep orange'
  logo: images/logo-lines.png
markdown_extensions:
  - codehilite
  - admonition  
  - meta
  - toc:
      permalink: true

site_url: https://guides.peruzal.com/xamarin-forms-guide
repo_url: https://github.com/Peruzal/xamarin-forms-guide
repo_name: Github

extra:
  disqus: 'xamarin-guides'  

copyright: 'Copyright &copy; 2019 - Peruzal'

# Customization
extra_javascript:
  - 'js/drift.js'
  - 'js/mixpanel.js'

extra:
  social:
    - type: 'globe'
      link: 'https://www.peruzal.com'
    - type: 'github'
      link: 'https://github.com/peruzal'
    - type: 'twitter'
      link: 'https://twitter.com/peruzal'
    - type: 'linkedin'
      link: 'https://za.linkedin.com/company/peruzal'  
        
nav:
  - Introduction to Xamarin Forms: introduction.md
  - XAML:
    - Introduction to XAML: xaml/introduction.md
    - Platform Specifics: xaml/on-platform.md
    - XAML Mark Extension: xaml/xaml-markup-extensions.md
  # - Pages:
  #   - Content Page: pages/content-page.md
  #   - Navigation Page: pages/navigation-page.md
  #   - Tabbed Page: pages/tabbed-page.md
  #   - Master Detail Page: pages/master-detail-page.md
  #   - Carousel Page: pages/carousel-page.md
  #   - Template Page: pages/template-page.md
  - Xamarin Forms Views: 
      - Label: views/label.md
      - Entry: views/entry.md
      - Button: views/buttons.md
      - Editor: views/editor.md
      - Image: views/image.md
      - Switch: views/switch.md
      - Stepper: views/stepper.md
      - Picker: views/picker.md
      - Date Picker: views/date-picker.md
      - Time Picker: views/time-picker.md
      - Slider: views/slider.md
      - Activity Indicator: views/activity-indicator.md
      - ProgressBar: views/progress-bar.md
      - BoxView: views/box-view.md
      - Frame: views/frame.md
      - Search Bar: views/search-bar.md
      - Toolbar: views/toolbar.md
      - List View: views/list-view.md
      - Table View: views/tableview.md
      - Map: views/map.md
      - Carousel View: views/carousel-view.md
      - Web View: views/web-view.md
  - Layouts:
      - Layout Options: layouts/layout-options.md
      - Stack Layout: layouts/stack-layout.md
      - Grid Layout: layouts/grid-layout.md
      - Absolute Layout: layouts/absolute-layout.md
      - Relative Layout: layouts/relative-layout.md
      # - Flex Layout: layouts/flex-layout.md
      - Scroll View: layouts/scroll-view.md
  - Navigation: 
    - Hierachical Navigation: navigation/hierachical-navigation.md
    - Tabbed Navigation: navigation/tabbed-navigation.md
    - Master Detail Navigation: navigation/master-detail-navigation.md
    - Swipe Navigation: navigation/carousel.md
    - Displaying Popups:
      - Normal Popups: navigation/pop-ups/pop-ups.md
      - Modal Popups: navigation/pop-ups/modal-pop-ups.md
  
  - Customizing ListView: customizing-listview.md
  - Styles and Resources: ui-styles.md
  - Networking: networking.md
  - Persistance and SQLite: 
      - Preferences: persistence/preferences.md
      - SQLite.NET: persistence/sqlite.md
  - Data Binding: data-binding.md
  - Model View-View Model(MVVM): mvvm.md
  - Dependency Injection: dependency-injection.md
  - Extending Controls with Behaviours: behaviours.md
  - Xamarin.Essentials Cross Platform API: xamarin-essentials.md
  # - Animation: animation.md
  - Platform Specifics: platform-specifics.md
  # - Design Resources: design-resources.md
  # - Tips: tips.md
